
package com.hcl.manish.engineer.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.hcl.manish.engineer.ws.ct.Employee;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2_01-hudson-189-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Engineer", targetNamespace = "http://manish.hcl.com/engineer/ws")
@XmlSeeAlso({
    com.hcl.manish.engineer.ws.ObjectFactory.class,
    com.hcl.manish.engineer.ws.ct.ObjectFactory.class
})
public interface Engineer {


    /**
     * 
     * @param y
     * @param x
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Add", action = "http://manish.hcl.com/engineer/ws/Add")
    @WebResult(name = "sum", targetNamespace = "")
    @RequestWrapper(localName = "Add", targetNamespace = "http://manish.hcl.com/engineer/ws", className = "com.hcl.manish.engineer.ws.Add")
    @ResponseWrapper(localName = "AddResponse", targetNamespace = "http://manish.hcl.com/engineer/ws", className = "com.hcl.manish.engineer.ws.AddResponse")
    public int add(
        @WebParam(name = "x", targetNamespace = "")
        int x,
        @WebParam(name = "y", targetNamespace = "")
        int y);

    /**
     * 
     * @param y
     * @param x
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Sub", action = "http://manish.hcl.com/engineer/ws/Sub")
    @WebResult(name = "value", targetNamespace = "")
    @RequestWrapper(localName = "Sub", targetNamespace = "http://manish.hcl.com/engineer/ws", className = "com.hcl.manish.engineer.ws.Sub")
    @ResponseWrapper(localName = "SubResponse", targetNamespace = "http://manish.hcl.com/engineer/ws", className = "com.hcl.manish.engineer.ws.SubResponse")
    public double sub(
        @WebParam(name = "x", targetNamespace = "")
        double x,
        @WebParam(name = "y", targetNamespace = "")
        double y);

    /**
     * 
     * @param addEmp
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AddEmployee", action = "http://manish.hcl.com/engineer/ws/AddEmployee")
    @WebResult(name = "AddEmpResp", targetNamespace = "")
    @RequestWrapper(localName = "AddEmployee", targetNamespace = "http://manish.hcl.com/engineer/ws", className = "com.hcl.manish.engineer.ws.AddEmployee")
    @ResponseWrapper(localName = "AddEmployeeResponse", targetNamespace = "http://manish.hcl.com/engineer/ws", className = "com.hcl.manish.engineer.ws.AddEmployeeResponse")
    public boolean addEmployee(@WebParam(name = "AddEmp", targetNamespace = "")Employee addEmp);

}
