package com.genuitec.hibernate;
// Generated by MyEclipse - Hibernate Tools



/**
 * EchoMessage generated by MyEclipse - Hibernate Tools
 */
public class EchoMessage extends AbstractEchoMessage implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public EchoMessage() {
    }

    
    /** full constructor */
    public EchoMessage(String msg) {
        super(msg);        
    }
   
}
